(venv) pi@pi:~/Documents/grad-proj $ python3 app.py 

============================================================
Starting Irrigation Control System Server
Local access:  http://localhost:5000
Network access: http://192.168.1.17:5000
============================================================

UI update interval: 1 seconds
Database update interval: 60 seconds

Checking connected devices:
------------------------------
------------------------------
Error reading DHT sensor: Checksum did not validate. Try again.
[2025-05-09 08:42:41,222] ERROR in app: Exception on /api/irrigation/presets [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 33, in get_presets
    from .controllers import get_presets
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:42:41,328] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:42:41,342] ERROR in app: Exception on /api/irrigation/presets [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 33, in get_presets
    from .controllers import get_presets
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:42:41,388] ERROR in app: Exception on /api/irrigation/presets [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 33, in get_presets
    from .controllers import get_presets
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:42:41,491] ERROR in app: Exception on /api/irrigation/presets [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 33, in get_presets
    from .controllers import get_presets
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:42:41,522] ERROR in app: Exception on /api/irrigation/presets [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 33, in get_presets
    from .controllers import get_presets
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:42:41,536] ERROR in app: Exception on /api/irrigation/presets [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 33, in get_presets
    from .controllers import get_presets
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
Error reading DHT sensor: A full buffer was not returned. Try again.
[2025-05-09 08:42:46,386] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
Error reading DHT sensor: A full buffer was not returned. Try again.
[2025-05-09 08:42:50,624] ERROR in app: Exception on /api/irrigation/pump/start [POST]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 19, in start_pump
    from .controllers import start_pump as controller_start_pump
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:42:51,410] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:42:51,707] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:42:52,240] ERROR in app: Exception on /api/irrigation/pump/stop [POST]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 26, in stop_pump
    from .controllers import stop_pump as controller_stop_pump
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
Error reading DHT sensor: Checksum did not validate. Try again.
[2025-05-09 08:42:53,471] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:42:56,427] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:42:56,773] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
Error reading DHT sensor: Checksum did not validate. Try again.
[2025-05-09 08:42:58,506] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
Error reading DHT sensor: Checksum did not validate. Try again.
[2025-05-09 08:43:01,453] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:43:01,794] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:43:03,528] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:43:06,476] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:43:06,811] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:43:08,542] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:43:11,497] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:43:11,829] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:43:13,562] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:43:16,510] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:43:16,843] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
[2025-05-09 08:43:18,584] ERROR in app: Exception on /api/irrigation/status [GET]
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Documents/grad-proj/irrigation/routes.py", line 9, in get_irrigation_status
    from .controllers import get_pump_status, get_water_level
  File "/home/pi/Documents/grad-proj/irrigation/controllers.py", line 16, in <module>
    pump = Relay(pin=17, name="Water Pump", simulation=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relay.__init__() got an unexpected keyword argument 'name'
^Creceived SIGINT

(venv) pi@pi:~/Documents/grad-proj $ 
